In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

Basic Operations of array

In [4]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


creating more than 1d array

In [5]:
#creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(a2.shape)

(2, 3)


In [7]:
print(a2.ndim)

2


In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
array = np.random.randint(1,11, size=(3,4))
print(array)

[[3 2 8 7]
 [3 1 7 2]
 [9 5 2 5]]


In [16]:
x = np.array([[7,2,3],
             [3,9,4],
             [3,4,5]])

y = np.array([[3,4,5],
            [3,9,4],
            [7,2,3]])

print(x)
print(y)

[[7 2 3]
 [3 9 4]
 [3 4 5]]
[[3 4 5]
 [3 9 4]
 [7 2 3]]


In [19]:
print(x*y)

[[21  8 15]
 [ 9 81 16]
 [21  8 15]]


In [17]:
print(x@y) #matrix multiplication

[[ 48  52  52]
 [ 64 101  63]
 [ 56  58  46]]


In [20]:
np.dot(x,y) #matrix multiplication

array([[ 48,  52,  52],
       [ 64, 101,  63],
       [ 56,  58,  46]])

In [21]:
x.prod() #product of all elements

np.int64(272160)

In [22]:
x.mean() #mean of all elements

np.float64(4.444444444444445)

In [23]:
y.mean()

np.float64(4.444444444444445)